apiVersion: apps/v1
kind: Deployment
metadata:
  name: svc-auth
  namespace: groupsapp
  labels: { app: svc-auth }
spec:
  replicas: 1
  selector:
    matchLabels: { app: svc-auth }
  template:
    metadata:
      labels: { app: svc-auth }
    spec:
      containers:
        - name: svc-auth
          image: dajaramilc/groupsapp-svc-auth:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8001
          envFrom:
            - secretRef: { name: app-secrets }
          resources:
            requests: { cpu: "50m", memory: "128Mi" }
            limits:   { cpu: "300m", memory: "256Mi" }
          readinessProbe:
            httpGet: { path: /health, port: 8001 }
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet: { path: /health, port: 8001 }
            initialDelaySeconds: 20
            periodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: svc-auth
  namespace: groupsapp
spec:
  selector: { app: svc-auth }
  ports:
    - port: 8001
      targetPort: 8001
