# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from app.grpc_proto import channels_pb2 as channels__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in channels_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ChannelServiceStub(object):
    """Servicio gRPC interno expuesto por svc-channels.
    Consumidores: svc-messages (verifica acceso antes de enviar mensajes).
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CheckChannelAccess = channel.unary_unary(
                '/groupsapp.channels.ChannelService/CheckChannelAccess',
                request_serializer=channels__pb2.CheckChannelAccessRequest.SerializeToString,
                response_deserializer=channels__pb2.CheckChannelAccessResponse.FromString,
                _registered_method=True)


class ChannelServiceServicer(object):
    """Servicio gRPC interno expuesto por svc-channels.
    Consumidores: svc-messages (verifica acceso antes de enviar mensajes).
    """

    def CheckChannelAccess(self, request, context):
        """Verifica si un usuario puede enviar mensajes en un canal.
        Resuelve: canal existe + usuario es miembro del grupo dueño del canal.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ChannelServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CheckChannelAccess': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckChannelAccess,
                    request_deserializer=channels__pb2.CheckChannelAccessRequest.FromString,
                    response_serializer=channels__pb2.CheckChannelAccessResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'groupsapp.channels.ChannelService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('groupsapp.channels.ChannelService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ChannelService(object):
    """Servicio gRPC interno expuesto por svc-channels.
    Consumidores: svc-messages (verifica acceso antes de enviar mensajes).
    """

    @staticmethod
    def CheckChannelAccess(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/groupsapp.channels.ChannelService/CheckChannelAccess',
            channels__pb2.CheckChannelAccessRequest.SerializeToString,
            channels__pb2.CheckChannelAccessResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
