# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: channels.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'channels.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x63hannels.proto\x12\x12groupsapp.channels\"@\n\x19\x43heckChannelAccessRequest\x12\x12\n\nchannel_id\x18\x01 \x01(\t\x12\x0f\n\x07user_id\x18\x02 \x01(\t\"c\n\x1a\x43heckChannelAccessResponse\x12\x0f\n\x07\x61llowed\x18\x01 \x01(\x08\x12\x12\n\nchannel_id\x18\x02 \x01(\t\x12\x10\n\x08group_id\x18\x03 \x01(\t\x12\x0e\n\x06reason\x18\x04 \x01(\t2\x85\x01\n\x0e\x43hannelService\x12s\n\x12\x43heckChannelAccess\x12-.groupsapp.channels.CheckChannelAccessRequest\x1a..groupsapp.channels.CheckChannelAccessResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'channels_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CHECKCHANNELACCESSREQUEST']._serialized_start=38
  _globals['_CHECKCHANNELACCESSREQUEST']._serialized_end=102
  _globals['_CHECKCHANNELACCESSRESPONSE']._serialized_start=104
  _globals['_CHECKCHANNELACCESSRESPONSE']._serialized_end=203
  _globals['_CHANNELSERVICE']._serialized_start=206
  _globals['_CHANNELSERVICE']._serialized_end=339
# @@protoc_insertion_point(module_scope)
